[package]
name = "Advent of Code 2018"
version = "0.1.0"
authors = ["Adrien Coulier <adrien.coulier@free.fr>"]

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day1b"
path = "src/day1b.rs"
