[package]
name = "Adven Calendar"
version = "0.1.0"
authors = ["Adrien Coulier <adrien.coulier@free.fr>"]

[dependencies]
rulinalg="0.4.2"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day1b"
path = "src/day1b.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day2b"
path = "src/day2b.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"

[[bin]]
name = "day4"
path = "src/day4.rs"

[[bin]]
name = "day4b"
path = "src/day4b.rs"

[[bin]]
name = "day5"
path = "src/day5.rs"

[[bin]]
name = "day5b"
path = "src/day5b.rs"

[[bin]]
name = "day6"
path = "src/day6.rs"

[[bin]]
name = "day6b"
path = "src/day6b.rs"

[[bin]]
name = "day7"
path = "src/day7.rs"

[[bin]]
name = "day8"
path = "src/day8.rs"

[[bin]]
name = "day8b"
path = "src/day8b.rs"

[[bin]]
name = "day9"
path = "src/day9.rs"

[[bin]]
name = "day9b"
path = "src/day9b.rs"
