[package]
name = "Advent_of_Code_2019"
version = "0.1.0"
authors = ["Adrien Coulier <adrien.coulier@free.fr>"]

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day1b"
path = "src/day1b.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"

[[bin]]
name = "day3b"
path = "src/day3b.rs"
