[package]
name = "Advent_of_Code_2019"
version = "0.1.0"
authors = ["Adrien Coulier <adrien.coulier@free.fr>"]

[dependencies]
itertools = "0.8.2"
num-integer = "0.1.41"
regex = "1.3.1"
rand = "0.5"
lazy_static = "1.4.0"
